@token = Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTU4NzM5NDM4NCwiZXhwIjoxNTg3NjEwMzg0LCJuYmYiOjE1ODczOTQzODQsImp0aSI6InhZUUE2NlRDTEkwT0ZYcmIiLCJzdWIiOjMwLCJwcnYiOiI4N2UwYWYxZWY5ZmQxNTgxMmZkZWM5NzE1M2ExNGUwYjA0NzU0NmFhIn0.SfO93Fr8E_IqE13lZ_5I62B3UxFyQMZdFLlqLSQWFFY
###V4nH4GTfKLhBwrNx
POST http://localhost:8000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email":"prueba@gn7app.com",
    "password":"test"
}
###
POST http://localhost:8000/api/conductor/actualizarEstado
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
    "estado":true
}
###
GET http://localhost:8000/api/conductor/ofertas
Authorization: {{token}}

###
GET http://localhost:8000/api/envio/rutas/17742
Accept: application/json
Authorization: {{token}}

###
GET http://localhost:8000/api/envio/iniciar/17408
Accept: application/json
Authorization: {{token}}

###
GET http://localhost:8000/api/envio/aceptar/17763
Accept: application/json
Authorization: {{token}}

###
GET http://localhost:8000/api/envio/finalizar/17429
Accept: application/json
Authorization: {{token}}

###
POST http://localhost:8000/api/pedido/actualizar
Accept: application/json
Authorization: {{token}}
Content-Type: application/json

{
    "idpedido_detalle": 326661,
    "estado": "ENTREGA EN AGENCIA",
    "observacion": "Direccion incompleta",
    "latitud": "-13.179256",
    "longitud": "-77.9949845"
}

###
GET http://localhost:8000/api/pedido/motivos/5
Accept: application/json
Authorization: {{token}}

###
GET http://localhost:8000/api/pedido/imagen/332260
Accept: application/json
Authorization: {{token}}

###
GET http://localhost:8000/api/pedido/agencias/31
Accept: application/json
Authorization: {{token}}